#!/bin/sh

# +────────────────────────────────────────────────────────────────────────────────────────────────────────────────────+
# | ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗     ██████╗ ██╗   ██╗ █████╗ ███╗   ██╗████████╗██╗   ██╗███╗   ███╗ |
# | ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║    ██╔═══██╗██║   ██║██╔══██╗████╗  ██║╚══██╔══╝██║   ██║████╗ ████║ |
# | ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║    ██║   ██║██║   ██║███████║██╔██╗ ██║   ██║   ██║   ██║██╔████╔██║ |
# | ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║    ██║▄▄ ██║██║   ██║██╔══██║██║╚██╗██║   ██║   ██║   ██║██║╚██╔╝██║ |
# | ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║    ╚██████╔╝╚██████╔╝██║  ██║██║ ╚████║   ██║   ╚██████╔╝██║ ╚═╝ ██║ |
# | ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝     ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝ |
# +────────────────────────────────────────────────────────────────────────────────────────────────────────────────────+

#Restore colorscheme
wal -R

#+──────────────────────────────────────────────+
#|             RESTORE WALLPAPER                |
#+──────────────────────────────────────────────+

feh --bg-fill $HOME/.wallpaper

#Other function for persistence, not working for pictures on unmounted disk
#feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"

#+──────────────────────────────────────────────+
#|                  WORKSPACES                  |
#+──────────────────────────────────────────────+

bspc monitor ${monitor} -n "screen" -d '一' '二' '三' '四' '五' '六' '七'
bspc config border_width         0
bspc config window_gap           10
bspc config split_ratio          0.50

#bspc config focused_border_color "#282828"
#bspc config normal_border_color "#1a1b26"
#bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

#+──────────────────────────────────────────────+
#|                 BSPWM RULES                  |
#+──────────────────────────────────────────────+

# workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal kitty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox brave)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on;done

# workspace 4 (Text Editor)
declare -a office=(Code Geany codium)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc mpv mplayer lxmusic Gimp Gimp-2.10 \
  VirtualBox Manager)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

#+──────────────────────────────────────────────+
#|                  AUTOSTART                   |
#+──────────────────────────────────────────────+

#Polybar
$HOME/.config/polybar/Japanese/launch.sh &

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww

# Launch notification daemon
dunst -config $HOME/.config/dunst/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Enable power management
xfce4-power-manager &

#Start compositor
picom &

#Start picom with nvidia gpu
#picom --experimental-backends --backend glx --xrender-sync-fence &

#Key map
setxkbmap us &
